//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Puppies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Puppies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Shared.Puppies", typeof(Puppies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Like all other Golden Retriever breeders, we also claim that we want to breed typical, good natured, healthy representatives of the breed – we love “sound nature”,
        ///      as our slogan says. Besides this, we have some special interests:
        ///    &lt;ul&gt;
        ///      &lt;li&gt;
        ///     we consciously look for sound, for less known and not so popular lines, since we consider their maintance essential for the breed&lt;/br&gt;
        ///      &lt;/li&gt;
        ///      &lt;li&gt;
        ///    we collect as much information as possible about the lines we use: visit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GRBreeders {
            get {
                return ResourceManager.GetString("GRBreeders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Since all of us have our main activities and jobs, in order to keep our hobby a hobby, we do not wish to breed many litters.
        ///        We do only the combinations we wish to continue with in principle and from which we would pick a dog for ourselves,
        ///        therefore we are open to collaboration with other breeders and the owners of our and our males’ progeny.
        ///        We are willing to build the dogs’ show careers, that is to prepare the dogs for and handle them at shows
        ///        (Tõnu and Heili [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LastPara {
            get {
                return ResourceManager.GetString("LastPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        The most commonly asked question is price — a well bred Golden Retriever or from a caring breeder will cost anything between &lt;strong&gt; 900—1300 EUR.
        ///        &lt;/strong&gt; This is quite an average price for pedigree dogs in Estonia today (they are more expensive abroad, starting from 1200 EUR),
        ///        and though Golden Retriever puppies are sometimes available much more cheaply, it is often from dubious sources or with questionable conditions.
        ///    .
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Our puppies are not cheap — we have too much respect for the breeders’ work prior to us (thanks to whom we have these dogs), our own dogs and ourselves for that.
        ///    .
        /// </summary>
        public static string Price1 {
            get {
                return ResourceManager.GetString("Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///            All puppies are ready to leave for new homes after they are 8 weeks old.
        ///            They are wormed, vaccinated, Estonian Kennel Club registered, and microchipped.
        ///            All puppies are reared in the home; they have access to the fresh air daily from 4-5 weeks of age in the garden.
        ///            They are allowed to explore inside our home and all are partially house trained before they leave.
        ///            Puppies are handled all the time, mix and play with the adult dogs and cats, and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Price2 {
            get {
                return ResourceManager.GetString("Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;strong&gt;Every puppy leaves home with extensive and detailed rearing guidelines and an information and starter pack.
        ///        We ask all puppy buyers to stay in touch and are thrilled to receive news and photos of our extended family.&lt;/strong&gt;
        ///        &lt;/br&gt;
        ///        &lt;/br&gt;
        ///        &lt;strong&gt;We ask all puppy buyers to sign a contract, as the Estonian Kennel Club advises.
        ///        This contract states amongst other things, that should you for whatever reason ever have to part with your dog,
        ///        t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PuppyLeaves {
            get {
                return ResourceManager.GetString("PuppyLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you consider a Ringokris puppy, please send an email (ringokris.goldens@gmail.com).
        ///    .
        /// </summary>
        public static string SoovKutsikatVotta {
            get {
                return ResourceManager.GetString("SoovKutsikatVotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Please let us have as much information about your family, home and circumstances, as well as your wishes and circumstances in regard of the dog.
        ///    Before deciding about the dog, please check that neither you nor any of your family members is allergic to dogs!.
        /// </summary>
        public static string SoovKutsikatVottaStrong {
            get {
                return ResourceManager.GetString("SoovKutsikatVottaStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StayTouch {
            get {
                return ResourceManager.GetString("StayTouch", resourceCulture);
            }
        }
    }
}
